apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: imagine-deployment
spec:
  selector:
    matchLabels:
      app: imagine
  replicas: 10
  template:
    metadata:
      labels:
        app: imagine
    spec:
      containers:
      - name: imagine
        image: joedursun/imagine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: imagine-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: imagine
